// Code generated by "stringer -type=State"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Validated-0]
	_ = x[Merge-1]
	_ = x[ArgumentMissing-2]
	_ = x[FileMissing-3]
	_ = x[ReadError-4]
	_ = x[EmptyMessage-5]
	_ = x[EmptyHeader-6]
	_ = x[BadHeaderFormat-7]
	_ = x[WrongType-8]
	_ = x[ScopeMissing-9]
	_ = x[WrongScope-10]
	_ = x[BodyMissing-11]
	_ = x[NoBlankLineBeforeBody-12]
	_ = x[LineOverLong-13]
	_ = x[UndefindedError-14]
}

const _State_name = "ValidatedMergeArgumentMissingFileMissingReadErrorEmptyMessageEmptyHeaderBadHeaderFormatWrongTypeScopeMissingWrongScopeBodyMissingNoBlankLineBeforeBodyLineOverLongUndefindedError"

var _State_index = [...]uint8{0, 9, 14, 29, 40, 49, 61, 72, 87, 96, 108, 118, 129, 150, 162, 177}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
